from enum import IntEnum


class SeverityCode(IntEnum):
    SC_EMERGENCY = 0
    SC_ALERT = 1
    SC_CRITICAL = 2
    SC_ERROR = 3
    SC_WARNING = 4
    SC_NOTICE = 5
    SC_INFORMATIONAL = 6
    SC_DEBUG = 7


MESSAGE_SEVERITY_IGNORE_MASK = 0x80
MESSAGE_SEVERITY_EXCLUDE_IGNORE_MASK = 0x7F


class MessageLogCode(IntEnum):
    MLC_NONE = 0

    # Empty EEPROM marker.
    MLC_NONE2 = 255

    MLC_SYSTEM_RESTART = 1
    MLC_SENSOR_FAILURE = 2
    MLC_CONTROLLER_ERROR = 3
    MLC_CONTROLLER_ERROR_IS_OK = 4
    MLC_MORE_THEN_ONE_OUTDOOR_SENSOR = 5
    MLC_ANTILEGION_PROTECTION_STARTED = 6
    MLC_ANTILEGION_PROTECTION_ENDED = 7
    MLC_BOILER_WARM_UP_STARTED = 8
    MLC_BOILER_WARM_UP_ENDED = 9
    MLC_OUTDOOR_TEMPERATURE_UNDEFINED = 10
    MLC_ALARM_STARTED = 11
    MLC_ALARM_RESET = 12
    MLC_ALARM_ENDED = 13
    MLC_CONSUMER_UNDERHEATING_START = 14
    MLC_CONSUMER_UNDERHEATING_OVER = 15
    MLC_LOW_PRESSURE_ALARM_STARTED = 16
    MLC_LOW_PRESSURE_ALARM_ENDED = 17
    MLC_VENTILATION_FILTER_ALARM_START = 18
    MLC_VENTILATION_FILTER_ALARM_STOP = 19
    MLC_VENTILATION_FIRE_ALARM_START = 20
    MLC_VENTILATION_FIRE_ALARM_STOP = 21
    MLC_DOUBLE_PUMP_FAILURE = 22
    MLC_DHW_LOW_TEMPERATURE_START = 23
    MLC_LOW_TEMPERATURE_STOP = 24
    MLC_EXT_CONTROLLER_I2C_ERROR = 25

    MLC_WATCHDOG_TRIGGERED = 26
    MLC_SELFTEST_RESULT = 27
    MLC_WIFI_DISCONNECTED = 28
    MLC_WIFI_RECONNECT = 29
    MLC_HC_FLOWERROR = 30
    MLC_HC_FLOWUNSELECTED = 31
    MLC_HC_TMAXPROTECT = 32
    MLC_BLUESCREEN_ERROR = 33
    MLC_BLUESCREEN_ASSERT = 34
    MLC_BLUESCREEN_EXCEPTION = 35
    MLC_CAN_BUS_NO_CONNECTION = 36
    MLC_CAN_BUS_CONNECTION_RESTORED = 37
    MLC_CAN_OVERFLOW = 38
    MLC_CAN_IDSET = 39
    MLC_VHCHCMAPPING_EVENT1 = 40
    MLC_VHCHCMAPPING_EVENT2 = 41
    MLC_VHCHCMAPPING_EVENT3 = 42
    MLC_SENSOR_ISBACK = 43

    MLC_CAN_AUTORESET_CONTROLLER_ID = 44
    MLC_CAN_ADD_CONTROLLER_ID = 45
    MLC_CAN_DELETE_CONTROLLER_ID = 46
    MLC_CAN_TEST_INFO = 47

    MLC_HC_FROSTPROTECT = 48
    MLC_HC_OVERLOADPROTECT = 49
    MLC_HC_DISCHARGEPROTECT = 50

    MLC_PROGRAM_VERY_LOW_TEMPERATURE = 51
    MLC_PROGRAM_VERY_HI_TEMPERATURE = 52

    MLC_FL_AUTO_FILL_STARTED = 53

    MLC_LIN_DEVICE_ERROR = 54
    MLC_LIN_DEVICE_NO_ERROR = 55

    MLC_LOW_POOL_WATER_LEVEL = 56
    MLC_CIRCULATION_ERROR = 57

    MLC_SOLAR_COLLECTOR_OVERHEAT = 58

    MLC_BOILER_ERROR = 59

    MLC_BOILER_POWER_IS_LOW = 60
    MLC_BOILER_TEMPERATURE_IS_LOW = 61

    MLC_BOILER_CONNECTION_ERROR = 62
    MLC_CONTROLLER_CONNECTION_ERROR = 63

    MLC_PROGRAM_INPUT_ERROR = 64

    MLC_CIRCULATION_NO_ERROR = 65

    MLC_CWC_SENSOR_MAPPED = 66
    MLC_CWC_SENSOR_MAPPING_FAIL = 67
    MLC_CWC_NOT_FOUND = 68

    MLC_CONTROLLER_RESTART_LOG = 69

    MLC_CASCADE_BOILER_ERROR = 70
